SET @rownum := 0;

SELECT A.ANIMAL_ID, COUNT(*) AS "COUNT"
FROM
(SELECT  @rownum := @rownum + 1 AS rownum, ANIMAL_ID, DATETIME, 
DATE_SUB(DATETIME, INTERVAL @rownum DAY) AS GROUP_DATE
FROM ANIMAL_OUTS
ORDER BY ANIMAL_ID ASC, DATETIME ASC) AS A
GROUP BY A.GROUP_DATE

HAVING COUNT >1;